basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Integration API
  version: "1.0"
paths:
  /ready:
    get:
      consumes:
      - application/json
      description: Returns a simple message indicating that the service is ready.
      produces:
      - application/json
      responses:
        "202":
          description: Hello Pullu
          schema:
            type: string
      summary: Ready API
      tags:
      - readyCheck
schemes:
- http
- https
swagger: "2.0"
