info:
  contact: {}
paths:
  /ready:
    get:
      consumes:
      - application/json
      description: Returns a simple message indicating that the service is ready.
      produces:
      - application/json
      responses:
        "202":
          description: Hello Pullu
          schema:
            type: string
      summary: Ready API
      tags:
      - health
swagger: "2.0"
